### ISSUE TITLE
Define and plan the requirements gathering for health check types from other BB developers

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#10]
Define plan and method/framework for the requirements gathering from other BB developers (questionnaire, one-on-one meetings, joint meetings etc.). 
Plan and perform outreach to other BB developers for requirements gathering.

**Comment by dovydas-an** [comment]
Outreach email template generated:

Dear **<Recipient>**,

I am a member of a Resource Health BB development team from Sensmetry (subcontractor from Space Application Services consortium) and I am writing to you because we would like to gather requirements and use cases from **<BB>** team that would tailor our design to allow greater interoperability between our and your BBs. In case that by mistake, I am reaching out to a wrong stakeholder, please refer me to the right person(s) that are involved in **<BB>** development.

We have prepared a set of questions that we would like to share with you. They are aimed to aid in beginning the discussion with you, thus we would like to ask you to allocate some time to review and think of answers to them.

_Our questions:
	1. What resources you (as BB developers and users of your BB) would need to monitor? E.g. datasets, workflows, web applications, etc.
	2. In natural language, how would you describe the function and nature of each check? E.g. Check that a workflow produces expected results on (test) input; Check that the dataset contains any data from the last 24h; Check that a dataset has the right columns; Check that a web application is available at an appropriate URL etc.
	3. Temporal questions - how often and when should each check run? E.g. when a new dataset is uploaded, once per day; 10 minutes after a web app is updated etc.
	4. What are the means available for accessing the BB information necessary to perform this monitoring (question of observability)? E.g. APIs, logs
	5. What are the relevant auxiliary sets of information which would help "debug" issues that arise? (we would want to display that to the user or at least point them to the relevant info). E.g. logs from workflow execution, dataset metadata, etc._

In addition, we would like to set up a live meeting with you to discuss your answers to our questions and address any additional comments/requests/considerations that you would like to raise with us. Thus, please let me know what time slots would suit you best in the near future (for us Wednesday to Friday afternoons would be the most suitable times, but we can accommodate a different time, if you prefer). Lastly, I would like to mention that we would prefer, if you could provide answers to the questions raised above prior to the live discussion, however if that is not possible, we can review and discuss them live.

Looking forward to collaborating with you and will be waiting for your reply!

**Comment by dovydas-an** [comment]
Contacted the following BB development teams/leads:
* Data Access
* DataCube Access
* Application Hub

**Comment by dovydas-an** [comment]
The preliminary plan for reqs gathering from other BB dev teams is:

1. Send the "initial outreach email" with:
   a. A set of questions that would aid in beginning the discussion.
   b. A request to set-up a live discussion to discuss the answers to the above-mentioned questions and any additional comments/questions.
2. Perform the "live discussion" and consequently update the reqs and use cases.
3. Whenever the implementation of RH BB includes the discussed functionality/capabilities in the "live discussion", expose the BB relevant other BB dev stakeholders to gather feedback.

Comment: all of the above steps 2 to 3 are to be repeated as many times as possible/feasible if time available for "Requirement and Roadmap Refinement" allows.

**Comment by tilowiklundSensmetry** [comment]
I think the list of priorities BBs is good, the questions/wording are reasonable. I would maybe suggest avoiding "What are" (precisely identifying this completely is probably a decently complex effort), and instead try to go for something that expresses "Which ones can you think of off the top of your head, right now"?
