### ISSUE TITLE
Update Resource Health BB documentation

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#14]
Maintain Resource Health BB documentation to make sure that it represents the latest status of development of the BB. In addition, before the end of development cycle, update the Resource Health BB documentation to make sure that it represents the latest status of development of the BB.

**Comment by dovydas-an** [comment]
- [ ] Additional request to publish preliminary plans for OpenTelemetry implementation and availability of functionality that enables other BBs to feed their own derived/specified telemetry into Resource Health BB.

**Comment by tilowiklundSensmetry** [comment]
Currently working on updating the design overview based on the design refinement we've done with help of the prototype the last two months.

**Comment by dovydas-an** [comment]
- [ ] User tutorial document (to allow early user's to work with the Resource Health BB) - Tilo
- [ ] Updated reqs and use cases - Dovydas

**Comment by tilowiklundSensmetry** [comment]
Basic "quick start" documentation in internal MR !10.

**Comment by dovydas-an** [comment]
Updated and refined requirements and use cases added in internal MR, soon to be ported to github repo (and will be published with the documentation).
