### ISSUE TITLE
Skeleton deployment of Resource Health BB

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#15]
Achieve a skeleton deployment of Resource Health BB on Kubernetes cluster (placeholder applications on ArgoCD).

**Comment by tilowiklundSensmetry** [comment]
We've had most of this skeleton for a while, the missing parts is:
- some simple placeholder test
- merge ArgoCD app yamls

**Comment by tilowiklundSensmetry** [comment]
The end-to-end test application has been updated with a simple web-ui (instead of the terminal application) and has been moved into the EOEPCA develop cluster repository https://github.com/EOEPCA/eoepca-plus/commit/f0ef09891922d4ce18e4ac3e51ba802d54715bdc
