### ISSUE TITLE
Preliminary support in checking library against user identity

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#16]
Implement preliminary support in checking library against user identity (the implemented functionality highly depends on the IAM BB implementation progress).

**Comment by tilowiklundSensmetry** [comment]
De-prioritised in favour of https://github.com/orgs/EOEPCA/projects/13/views/1?pane=issue&itemId=78710871&issue=EOEPCA%7Cresource-health%7C19

Will be taken up again as part of IAM development in next quarter.
