### ISSUE TITLE
Update the design overview documentation

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#18]
> Currently working on updating the design overview based on the design refinement we've done with help of the prototype the last two months.

_Originally posted by @tilowiklundSensmetry in https://github.com/EOEPCA/resource-health/issues/14#issuecomment-2324756566_

**Comment by tilowiklundSensmetry** [comment]
A complete draft is in MR1. Still requires drawing out some pictures and examples, but I will delay that until later, moving this into review.
