### ISSUE TITLE
Identity/security architecture example with document level access

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#19]
> We've done a sanity check of using OpenSearch for storage either for writing directly with otel-collector or through Jaeger and then consuming the data. OpenSearch dashboards (with the observability extension) may be lacking as a dashboarding solution (we should write out this assessment properly), but useful at least for development purposes right now. **A major component missing (that should probably be its own ticket) is the identity/security architecture, where we want to do an end-to-end example with document level access.**

_Originally posted by @tilowiklundSensmetry in https://github.com/EOEPCA/resource-health/issues/9#issuecomment-2324708066_

**Comment by tilowiklundSensmetry** [comment]
Done, but for now in an internal repo until it can be integrated into the reference deployment. This will be done once the IAM situation on the EOEPCA development cluster gets clearer.
