### ISSUE TITLE
Implementation of RH check UI dashboard demo app

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#20]
> We've done a sanity check of using OpenSearch for storage either for writing directly with otel-collector or through Jaeger and then consuming the data. **OpenSearch dashboards (with the observability extension) may be lacking as a dashboarding solution (we should write out this assessment properly), but useful at least for development purposes right now.** A major component missing (that should probably be its own ticket) is the identity/security architecture, where we want to do an end-to-end example with document level access. 

 _Originally posted by @tilowiklundSensmetry in [#9](https://github.com/EOEPCA/resource-health/issues/9#issuecomment-2324708066)_

Since it has been identified that the OpenSearch dashboard tool is insufficient for the purposes of RH BB, it was decided to implement a custom dashboard app.

**Comment by dovydas-an** [comment]
@Jonas-Puksta-Sensmetry just wanted to verify, if this is already finished and ready for review or even Done?

**Comment by Jonas-Puksta-Sensmetry** [comment]
Yes, the basic version is done.
