### ISSUE TITLE
Validation of OpenSearch for backend storage and dashboard visualization

### ISSUE THREAD

**Issue by dovydas-an** [EOEPCA/resource-health#9]
Open search deployment and OpenSearch dashboards with TLS & certificate management.

**Comment by tilowiklundSensmetry** [comment]
We've done a sanity check of using OpenSearch for storage either for writing directly with otel-collector or through Jaeger and then consuming the data. OpenSearch dashboards (with the observability extension) may be lacking as a dashboarding solution (we should write out this assessment properly), but useful at least for development purposes right now. A major component missing (that should probably be its own ticket) is the identity/security architecture, where we want to do an end-to-end example with document level access.
